// bootstrap — Spring Boot 진입점. 모든 모듈을 통합하고 웹 계층을 구동한다.
plugins {
    id("todakun.spring-boot")
}

dependencies {
    implementation(project(":common-web"))
    implementation(project(":common-persistence"))
    implementation(project(":auth:domain"))
    implementation(project(":auth:application"))
    implementation(project(":auth:adapter-in"))
    implementation(project(":auth:adapter-out"))
    implementation(project(":member:domain"))
    implementation(project(":member:application"))
    implementation(project(":member:adapter-in"))
    implementation(project(":member:adapter-out"))
    implementation(project(":saju:domain"))
    implementation(project(":saju:application"))
    implementation(project(":saju:adapter-in"))
    implementation(project(":saju:adapter-out"))
    implementation(project(":terms:domain"))
    implementation(project(":terms:application"))
    implementation(project(":terms:adapter-in"))
    implementation(project(":terms:adapter-out"))
    implementation(project(":luck:domain"))
    implementation(project(":luck:application"))
    implementation(project(":luck:adapter-in"))
    implementation(project(":luck:adapter-out"))
    implementation(project(":notification:domain"))
    implementation(project(":notification:application"))
    implementation(project(":notification:adapter-in"))
    implementation(project(":notification:adapter-out"))
    implementation(project(":fortune:domain"))
    implementation(project(":fortune:application"))
    implementation(project(":fortune:adapter-in"))
    implementation(project(":fortune:adapter-out"))

    implementation(libs.jackson.module.kotlin)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)
    implementation(libs.spring.boot.starter.security)
    implementation(libs.sentry.spring.boot4.starter)
    implementation(libs.springdoc.openapi.starter.webmvc.ui)
    runtimeOnly(libs.postgresql)

    testImplementation(project(":shared"))
    testImplementation(libs.spring.boot.test)
    testImplementation(libs.spring.boot.test.autoconfigure)
    testImplementation(libs.spring.boot.webmvc.test)
    testImplementation(libs.spring.test)
    testImplementation(libs.spring.security.test)
    testImplementation(libs.springmockk)
    testImplementation(libs.kotest.extensions.spring)
    testImplementation(libs.testcontainers.postgresql)
    testImplementation(libs.testcontainers.core)
    testImplementation(libs.testcontainers.junit.jupiter)
    testImplementation(libs.spring.boot.testcontainers)
}
