package com.yapp.todakun.dailyfortune.exception

import com.yapp.todakun.common.exception.BadRequestException
import com.yapp.todakun.dailyfortune.code.DailyFortuneErrorCode

class DailyFortuneItemCountMismatchException : BadRequestException(DailyFortuneErrorCode.DAILY_FORTUNE_ITEM_COUNT_MISMATCH)
