name: PR/Issue Writer Assigner

on:
  pull_request_target:
    types: [ opened, reopened ]
  issues:
    types: [ opened, reopened ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author as Assignee (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.ACTIONS_SECRET_TOKEN }}
          script: |
            const assignees = [context.payload.pull_request.user.login];
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: assignees
            });
      - name: Assign author as Assignee (Issue)
        if: github.event_name == 'issues'
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.ACTIONS_SECRET_TOKEN }}
          script: |
            const assignees = [context.payload.issue.user.login];
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: assignees
            });
